name: main
env:
  ARGO_NAMESPACE: argo
  ARGO_VERSION: v3.4.1

permissions:
  packages: write
  contents: read
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: self-hosted
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - name: publish image and chart
        run: |
          echo "Install argo"
          # Download the binary
          curl -sLO https://github.com/argoproj/argo-workflows/releases/download/${ARGO_VERSION}/argo-linux-amd64.gz
          # Unzip
          gunzip argo-linux-amd64.gz
          # Make binary executable
          chmod +x argo-linux-amd64
          echo "commit sha ${GITHUB_SHA}"
          ./argo-linux-amd64 version --short
          ./argo-linux-amd64 submit .argo/publish.yaml \
            --generate-name="${GITHUB_REPOSITORY_NAME_PART}-publish-${GITHUB_SHA_SHORT}-" \
            -p appName="${GITHUB_REPOSITORY_NAME_PART}" \
            -p branch="${GITHUB_REF_NAME}" \
            -p containerRegistryURL="ghcr.io/konstructio/${GITHUB_REPOSITORY_NAME_PART}:${GITHUB_SHA_SHORT}" \
            -p gitUrlNoProtocol="git@github.com:${GITHUB_REPOSITORY_OWNER_PART_SLUG}" \
            -p shortSha="${GITHUB_SHA_SHORT}" \
            -p ghRepo="${GITHUB_REPOSITORY_NAME_PART}" \
            -p ghUser="konstruct-bot" \
            -p ghToken=${{ secrets.GITHUB_TOKEN }} \
            -p ghOrg="${GITHUB_REPOSITORY_OWNER_PART_SLUG}" \
            -p ociRegistry="ghcr.io" \
            --wait --log
